### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mjkaufer** [mjkaufer/Messer#1]
```
Unhandled rejection TypeError: Cannot read property 'type' of null

    at callback (/Users/me/.node/lib/node_modules/messer/index.js:31:17)

    at /Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/src/listen.js:141:7

    at tryCatcher (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:24:31)

    at Promise._settlePromiseFromHandler (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:454:31)

    at Promise._settlePromiseAt (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:530:18)

    at Promise._settlePromises (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:646:14)

    at Async._drainQueue (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:182:16)

    at Async._drainQueues (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:192:10)

    at Immediate.Async.drainQueues [as _onImmediate] (/Users/me/.node/lib/node_modules/messer/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)

    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Seems to be triggered after a certain amount of time. Maybe a memory leak?

**Comment by bsansouci** [comment]
We're running a [bot](https://github.com/bsansouci/marc-zuckerbot) on a heroku server 24/7 and we never had this error :/

**Comment by mjkaufer** [comment]
¯\_(ツ)_/¯

**Comment by tomquirk** [comment]
Old issue, closing
