### ISSUE TITLE
Can'i install Messer on Raspberry Pi

### ISSUE THREAD

**Issue by mooooonbaby** [mjkaufer/Messer#102]
I'm running Raspbian Stretch on my Raspberry Pi with Node.js 10.15.3 and npm 6.4.1. When i try to install Messer with

npm install -g messer

i have the error

```
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-19T08_58_44_427Z-debug.log
```

and when i try it with 'sudo' there is this error

```
sudo npm install -g messer
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-8143ea22': Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-19T08_59_39_801Z-debug.log
```

It seems there are some problems with write permissions to some folders but i don't understand why root can write here.

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by mooooonbaby** [comment]
I dont think this is a Problem with Messer, i think it a Problem with npm. Problem still exists.

**Comment by tomquirk** [comment]
Yeah okay. In this case, I would just clone the repository directly and run `npm start` :)

**Comment by mooooonbaby** [comment]
ok, i've cloned it with 'git clone <link> and cd into ~/Messer. Then i run 'npm start' and get this error:

```
npm start
> messer@0.5.1 start /home/pi/Messer
> node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/Messer/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messer@0.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the messer@0.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-26T11_18_46_149Z-debug.log
```

What node_modules are missing? Is there still an other package.json?

**Comment by tomquirk** [comment]
did you `npm install` ?

**Comment by mooooonbaby** [comment]
Seems this works. I can start messer with npm start when i'm in the folder. But how can i start messer in a shell script?

npm start /path/to/messer doesn't work.

**Comment by tomquirk** [comment]
try `node path/to/messer/index.js` instead

**Comment by mooooonbaby** [comment]
Yes, this works. Thanks. Also non-interactive mode works

**Comment by mooooonbaby** [comment]
Seems there are some problems with the login because facebook has disabled the account. when i try to login with my browser i have to enter my mobile number - what i don't want to do. i want to try it with a new facebook acount.

messer cleanup should be enough to delete all login information that are saved in my home dir? can i check this? where are the files with the login information?
