### ISSUE TITLE
Cleanup ends with error

### ISSUE THREAD

**Issue by mooooonbaby** [mjkaufer/Messer#104]
Hi,

on my raspberry pi i had to install messer by unpacking the tar, cd into the folder and run 'npm install'. i can start messer with 'node /path/to/app/index.js' and this worked for a while. yesterday facebook has blocked my account and i had to give them my mobile phone number. i don't want to do this. so i created a new facebook account and tried to cleanup messer. this worked on ubuntu (here i could install messer normally using 'pip install') but not on my raspberry pi. when i run

`node /home/pi/bin/messer/index.js cleanup`

i have the error

```
(node:28658) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'logout' of undefined
    at /home/pi/bin/messer/node_modules/messen/dist/api.js:72:20
    at new Promise (<anonymous>)
    at Object.logout (/home/pi/bin/messer/node_modules/messen/dist/api.js:71:12)
    at Messen.<anonymous> (/home/pi/bin/messer/node_modules/messen/dist/messen.js:187:43)
    at step (/home/pi/bin/messer/node_modules/messen/dist/messen.js:32:23)
    at Object.next (/home/pi/bin/messer/node_modules/messen/dist/messen.js:13:53)
    at /home/pi/bin/messer/node_modules/messen/dist/messen.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/bin/messer/node_modules/messen/dist/messen.js:3:12)
    at Messen.logout (/home/pi/bin/messer/node_modules/messen/dist/messen.js:183:16)
    at Messer.logout (/home/pi/bin/messer/src/messer.js:131:22)
    at Object.<anonymous> (/home/pi/bin/messer/index.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
(node:28658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:28658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.2** has just been published, and this issue was fixed! Install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬
