### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by pniedzwiedzinski** [mjkaufer/Messer#121]
### Description

I tried to install it in docker container (`node:lts-stretch-slim`) and it's failing.

### Steps to Reproduce

1. My Dockerfile:
```
FROM node:lts-stretch-slim
RUN npm install -g messer
```

**Expected behavior:** To install messer

**Actual behavior:** 
```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/Schmavery/facebook-chat-api.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-16T22_05_12_688Z-debug.log
```

### Versions

Run, and copy-paste the results, of the following:
  - npm -v 6.4.1
  - node -v 10.15.3
  - messer -v -

Also, please include the OS and what version of the OS you're running.
`node:lts-stretch-slim`

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by pniedzwiedzinski** [comment]
Also here is content of .log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'messer' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session 35b9765765c9fdf9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/messer 417ms
8 silly pacote tag manifest for messer@latest fetched in 451ms
9 timing stage:loadCurrentTree Completed in 716ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule messer@0.5.2 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/chalk 109ms
18 silly pacote range manifest for chalk@^2.4.2 fetched in 119ms
19 silly resolveWithNewModule chalk@2.4.2 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/messen 237ms
21 http fetch GET 200 https://registry.npmjs.org/minimist 237ms
22 http fetch GET 200 https://registry.npmjs.org/mkdirp 238ms
23 http fetch GET 200 https://registry.npmjs.org/prompt 248ms
24 silly pacote version manifest for messen@1.0.0-beta.8 fetched in 273ms
25 silly resolveWithNewModule messen@1.0.0-beta.8 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz 152ms
27 http fetch GET 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz 145ms
28 http fetch GET 200 https://registry.npmjs.org/prompt/-/prompt-1.0.0.tgz 142ms
29 silly pacote range manifest for minimist@^1.2.0 fetched in 405ms
30 silly resolveWithNewModule minimist@1.2.0 checking installable status
31 silly pacote range manifest for prompt@^1.0.0 fetched in 405ms
32 silly resolveWithNewModule prompt@1.0.0 checking installable status
33 silly pacote range manifest for mkdirp@^0.5.1 fetched in 406ms
34 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 92ms
36 http fetch GET 200 https://registry.npmjs.org/ansi-styles 96ms
37 http fetch GET 200 https://registry.npmjs.org/supports-color 94ms
38 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 144ms
39 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
40 silly pacote range manifest for supports-color@^5.3.0 fetched in 144ms
41 silly resolveWithNewModule supports-color@5.5.0 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz 71ms
43 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 176ms
44 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
45 http fetch GET 200 https://registry.npmjs.org/color-convert 62ms
46 silly pacote range manifest for color-convert@^1.9.0 fetched in 69ms
47 silly resolveWithNewModule color-convert@1.9.3 checking installable status
48 http fetch GET 200 https://registry.npmjs.org/color-name 80ms
49 http fetch GET 200 https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz 65ms
50 silly pacote version manifest for color-name@1.1.3 fetched in 157ms
51 silly resolveWithNewModule color-name@1.1.3 checking installable status
52 http fetch GET 200 https://registry.npmjs.org/has-flag 74ms
53 http fetch GET 200 https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz 59ms
54 silly pacote range manifest for has-flag@^3.0.0 fetched in 140ms
55 silly resolveWithNewModule has-flag@3.0.0 checking installable status
56 silly fetchPackageMetaData error for facebook-chat-api@github:Schmavery/facebook-chat-api Error while executing:
56 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/Schmavery/facebook-chat-api.git
56 silly fetchPackageMetaData
56 silly fetchPackageMetaData undefined
56 silly fetchPackageMetaData No git binary found in $PATH
57 http fetch GET 200 https://registry.npmjs.org/readline 83ms
58 silly pacote range manifest for readline@^1.3.0 fetched in 88ms
59 silly resolveWithNewModule readline@1.3.0 checking installable status
60 http fetch GET 200 https://registry.npmjs.org/winston 112ms
61 silly pacote range manifest for winston@^3.1.0 fetched in 117ms
62 silly resolveWithNewModule winston@3.2.1 checking installable status
63 http fetch GET 200 https://registry.npmjs.org/dotenv 945ms
64 silly pacote range manifest for dotenv@^6.2.0 fetched in 951ms
65 silly resolveWithNewModule dotenv@6.2.0 checking installable status
66 timing stage:rollbackFailedOptional Completed in 3ms
67 timing stage:runTopLevelLifecycles Completed in 2686ms
68 verbose stack Error: No git binary found in $PATH
68 verbose stack     at checkGit (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:246:17)
68 verbose stack     at spawnGit (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:204:10)
68 verbose stack     at pinflight (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:131:12)
68 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
68 verbose stack     at Promise._execute (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:303:9)
68 verbose stack     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:483:18)
68 verbose stack     at new Promise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
68 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
68 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
68 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
68 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
68 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
68 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
68 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
68 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
68 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
69 verbose cwd /
70 verbose Linux 4.9.93-linuxkit-aufs
71 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "messer"
72 verbose node v10.15.3
73 verbose npm  v6.4.1
74 error code ENOGIT
75 error Error while executing:
75 error undefined ls-remote -h -t ssh://git@github.com/Schmavery/facebook-chat-api.git
75 error
75 error undefined
75 error No git binary found in $PATH
76 error Failed using git.
76 error Please check if you have git installed and in your PATH.
77 verbose exit [ 1, true ]
```

**Comment by pniedzwiedzinski** [comment]
Ok, I found a solution. That's of course caused by git which is not installed. 

https://stackoverflow.com/questions/53247394/npm-install-web3-install-fails-undefined-ls-remote
