### ISSUE TITLE
Cannot send some special characters in lock-on mode

### ISSUE THREAD

**Issue by rasca0027** [mjkaufer/Messer#135]
### Description

> When you try to send special characters (!,?,Chinese characters) without the prefix of English characters it fails

### Steps to Reproduce

1. Lock-on a conversation 
2. Try to send `!` or `?` or Chinese characters without any English characters in the front

**Expected behavior:** [What you expect to happen]

Message gets sent correctly

**Actual behavior:** [What actually happens]

```
Thrown:
TypeError: Cannot set property '1' of null
    at Messer.processCommand (/usr/local/lib/node_modules/messer/src/messer/index.js:167:15)
    at REPLServer.eval (/usr/local/lib/node_modules/messer/src/messer/index.js:109:23)
    at bound (domain.js:420:14)
    at REPLServer.runBound [as eval] (domain.js:433:12)
    at REPLServer.onLine (repl.js:700:10)
    at REPLServer.emit (events.js:209:13)
    at REPLServer.EventEmitter.emit (domain.js:476:20)
    at REPLServer.Interface._onLine (readline.js:316:10)
    at REPLServer.Interface._line (readline.js:693:8)
    at REPLServer.Interface._ttyWrite (readline.js:1019:14)
    at REPLServer.self._ttyWrite (repl.js:777:7)
    at ReadStream.onkeypress (readline.js:191:10)
    at ReadStream.emit (events.js:209:13)
    at ReadStream.EventEmitter.emit (domain.js:476:20)
    at emitKeys (internal/readline/utils.js:433:14)
    at emitKeys.next (<anonymous>)
```

### Versions

Run and copy-paste the results of the following:

- npm -v 6.13.0
- node -v 12.10.0
- messer -v 0.6.0

on Mac OS: Mojave (10.14.6)

**Comment by ethan-ou** [comment]
This seems to be because at `src/messer/src/index.js`, at [line 159](https://github.com/mjkaufer/Messer/blob/91892b26f7f2965d263dc3e2f9ebe785a8194ad0/src/messer/index.js#L159), the regex only matches when a message starts with a letter.

Original code:
```javascript
const argv = rawCommand.match(/([A-z]+).*/);
  
  // if we're in a lock, hack args to use the `message` command
  if (this.lock.isLocked()) {
    if (rawCommand === "--unlock\n") {
       //continued...
  }

```

We can potentially fix this by matching with a different regex once the user is in locked mode.

```javascript
let argv = rawCommand.match(/([A-z]+).*/);
  
  // if we're in a lock, hack args to use the `message` command
  if (this.lock.isLocked()) {
    argv = rawCommand.match(/.*/); //Added
    if (rawCommand === "--unlock\n") {
      //continued...
  }
```

**Comment by tomquirk** [comment]
@ethan-ou great idea! I like it and I think it will work well. I'll happily review/merge a PR for this
