### ISSUE TITLE
Getting only errors (when I'm logged in)

### ISSUE THREAD

**Issue by Nemesis77swe** [mjkaufer/Messer#138]
I've encountered only errors with this app.
First I had issues with logging in, but when I changed to a less complicated password (without }\{€`•{°•××`>chars) I got in, but now I'm only getting errors..

`Logging in...
Successfully logged in as Jonas Larsson
> message adam larsson
(node:2627) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:2627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> settings
(node:2627) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:2627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)`

I'm not sure if I'm missing something..
I'm running Ubuntu 18.04.3 mini 

npm -v
3.5.2
node -v
v8.10.0
messer -v
0.7.1

This is just that kind of app I was looking for..
Got any ideas?

**Comment by Nemesis77swe** [comment]
The issue has actually solved it "self", I installed puppeteer and it's dependencies, and after that I was just going to test messenger before uninstalling it, but then it worked..
I can't specify exactly which stuff that was added, because it was a lot of stuff..

**Comment by Nemesis77swe** [comment]
A little post op notice, it apparently needed node 10.x, and I only had 8.x installed, maybe should be added as dependency..
