### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by krunoPeric** [mjkaufer/Messer#155]
### Description
>Login to facebook works, but any command I try results in an error.

### Steps to Reproduce

1. `$ sudo apt install npm`
2.  `$ sudo npm install -g messer`
3. `$ messer`
4. now login using your facebook account credentials (the login works successfully)
5. `> contacts`

**Expected behavior:** 

Contact list is printed.

**Actual behavior:** 

the following error is the output:

>(node:8332) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Versions

- npm -v:  `3.5.2`
- node -v:  `v8.10.0`
- messer -v:  `0.7.2`

**Operating System Version:**
- lsb_release -d:  `Description:	Ubuntu 18.04.4 LTS`
- uname -r: `5.3.0-59-generic`

### Additional Information
It doesn't matter what I type in for the command -- any text input produces the same error.

**Comment by krunoPeric** [comment]
This is a duplicate of issue #150 so I closed it.
