### ISSUE TITLE
[DEB0018] Error

### ISSUE THREAD

**Issue by ChristianPyth** [mjkaufer/Messer#160]
### Description

> Prints out error [DEP0018]
> christian@Flamethrower:~$ messer
Logging in...
Successfully logged in as *censored*
> m *censored* test
(node:3552) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:3552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Steps to Reproduce

1. Log in
2. Write a message
3. Error

**Expected behavior:**  Work

**Actual behavior:** Don't work

### Versions

Run and copy-paste the results of the following:

- npm -v = 3.2.5
- node -v 8.10.0
- messer -v  0.7.3

Ubuntu Mate 18.04

### Additional Information

Not sure

**Comment by trfd** [comment]
I get the exact same error on Windows 10 for any messer command.
I tried it from a new clean install.
Configuration 
* Windows 10 (1903)
* npm -v 5.6.0
* node -v v8.9.4
* messer -v 0.7.3
