### ISSUE TITLE
bug in the new version 

### ISSUE THREAD

**Issue by chauchinyiu** [mjkaufer/Messer#39]
when i run messer, i got the following bug
messer ~/.config/config.json
/usr/local/lib/node_modules/messer/src/command-handlers.js:125
      )
      ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/messer/index.js:8:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)

**Comment by tomquirk** [comment]
hey @chauchinyiu , can we get the version of Node you're running?

**Comment by steamfire** [comment]
Similar error, installing today using Node@v9.2.0 npm@5.5.1:

macbookpro3:~ steamfire$ messer
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at ReadFileContext.fs.readFile [as callback] (/Users/steamfire/.npm-global/lib/node_modules/messer/src/helpers.js:50:39)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)

**Comment by tomquirk** [comment]
Thanks @steamfire, I'll look into that today

**Comment by tomquirk** [comment]
I'm on holidays rn, perhaps some else can look at fixing. It looks like there's a bug in the read file code for reading a credentials file

**Comment by tomquirk** [comment]
fixed! thanks @billcccheng
