### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by riley-martine** [mjkaufer/Messer#45]
I installed messer with `sudo npm install -g messer`

I logged in, using 2fa, and typed `contacts`.

This gave me the error:
`TypeError: Object.values is not a function
    at Promise (/usr/lib/node_modules/messer/src/command-handlers.js:119:34)
    at Messer.contacts (/usr/lib/node_modules/messer/src/command-handlers.js:118:12)
    at Messer.processCommand (/usr/lib/node_modules/messer/index.js:150:25)
    at REPLServer.eval (/usr/lib/node_modules/messer/index.js:128:54)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:539:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:232:10)
    at REPLServer.Interface._line (readline.js:583:8)
    at REPLServer.Interface._ttyWrite (readline.js:860:14)
    at REPLServer.self._ttyWrite (repl.js:612:7)
    at ReadStream.onkeypress (readline.js:119:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
`

I then tried `history "$NAME"`

`Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /usr/lib/node_modules/messer/node_modules/facebook-chat-api/utils.js:843:42
    at tryCatcher (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/method.js:31:24)
    at /usr/lib/node_modules/messer/node_modules/facebook-chat-api/utils.js:813:24
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
`

Do I have the wrong version of some library maybe?

**Comment by tomquirk** [comment]
I'm gonna guess you're on an old version of npm. If you're okay to update it is recommended doing so.

I'll determine what the lowest compatible npm version is and update the docs and possibly add a warning in code

**Comment by riley-martine** [comment]
I updated to 5.6.0, but am still getting the error.

**Comment by davoodharun** [comment]
I ran into this too with:
node: v.6.11.5
npm: 3.10.10

I upgrade to:
node: v8.9.3
npm: 5.5.1
and it worked. 

Looks like Object.values is a relatively new feature in node and only stable in versions >7. I would try upgrading your node version.

**Comment by mjkaufer** [comment]
I'll try to implement a fix that doesn't require such a bleeding edge version of node

**Comment by mjkaufer** [comment]
I think I resolved this - try pulling version `0.2.2` npm and let me know if it still doesn't work, and I'll re-open the issue

**Comment by riley-martine** [comment]
Still getting the error with 0.2.2.
Updated node to 8.9.3 and error is fixed

**Comment by mjkaufer** [comment]
Hey @riley-martine can you print your full stack trace about `Object.values` not being a function with `0.2.2` on your old node version? I thought I removed all instances of `Object.values`, so there might be a dependency calling it or something.

**Comment by tomquirk** [comment]
@riley-martine would you be able to check if you are still experiencing this issue?
