### ISSUE TITLE
History Functionality Broken

### ISSUE THREAD

**Issue by mjkaufer** [mjkaufer/Messer#47]
When using the history command I get something like this...

```
> h "Anthony" 5
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at /Users/matthewkaufer/GitHub/Messer/node_modules/facebook-chat-api/utils.js:843:42
    at tryCatcher (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/method.js:31:24)
    at /Users/matthewkaufer/GitHub/Messer/node_modules/facebook-chat-api/utils.js:813:24
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/matthewkaufer/GitHub/Messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I'm pretty sure it's an issue with the facebook-chat-api dependency – I'm gonna leave an issue over there and see if they know what's up

**Comment by mjkaufer** [comment]
Update: Lots of people have the same problem and recommend using the `getThreadHistoryGraphQL` method instead, as per https://github.com/Schmavery/facebook-chat-api/issues/561

**Comment by tomquirk** [comment]
Lgtm 😀

**Comment by tomquirk** [comment]
This kind of works now 😄
