### ISSUE TITLE
Cannot read property 'name'

### ISSUE THREAD

**Issue by kubikmxm** [mjkaufer/Messer#48]
Hello!

Everything working well but today i updated to 0.2.2, and connected well! But i get this error message everytime on every command :

>$> m "pauline bln" test
TypeError: Cannot read property 'name' of undefined
    at Messer.getThreadByName (/usr/lib/node_modules/messer/index.js:186:34)
    at Promise (/usr/lib/node_modules/messer/src/command-handlers.js:83:29)
    at new Promise (<anonymous>)
    at Messer.message (/usr/lib/node_modules/messer/src/command-handlers.js:73:12)
    at Messer.processCommand (/usr/lib/node_modules/messer/index.js:150:25)
    at REPLServer.eval (/usr/lib/node_modules/messer/index.js:128:54)
    at bound (domain.js:370:14)
    at REPLServer.runBound [as eval] (domain.js:383:12)
    at REPLServer.onLine (repl.js:497:10)
    at REPLServer.emit (events.js:160:13)
    at REPLServer.Interface._onLine (readline.js:287:10)
    at REPLServer.Interface._line (readline.js:640:8)
    at REPLServer.Interface._ttyWrite (readline.js:920:14)
    at REPLServer.self._ttyWrite (repl.js:566:7)
    at ReadStream.onkeypress (readline.js:165:10)
    at ReadStream.emit (events.js:160:13)
$> m "pauline blna" test
User 'pauline blna' could not be found in your friends list!
$>

In fact, when a command is valide, messer show me this error. 
Only the contact command works.

I think this is related to this issue : [here](https://github.com/Schmavery/facebook-chat-api/issues/494).

Best regards :)

node v9.4.0
npm v5.6.0

**Comment by tomquirk** [comment]
Hmm, looks like the thread cache isn't being initialised. Should be a quick fix, I'll keep you posted

**Comment by tomquirk** [comment]
Update: looks like a problem with facebook-chat-api not returning list of threads. Will investigate

**Comment by tomquirk** [comment]
https://github.com/Schmavery/facebook-chat-api/issues/570 - looks like someone's got a GraphQL version in the works. Unfortunately, there's not much we can do at this point 😢

**Comment by ravkr** [comment]
you can use my version (https://github.com/ravkr/facebook-chat-api) with graphQL function
but you know... it can change at any moment and is not finished yet
