### ISSUE TITLE
A few days ago messer stopped working

### ISSUE THREAD

**Issue by Canardian** [mjkaufer/Messer#52]
I am running in a facebook chat group with 3 people. It worked fine until a few days ago. Then I started to get this error message when people send a message to the chat group:
```
> Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at c:\Users\mika\AppData\Roaming\npm\node_modules\facebook-chat-api\utils.js:843:42
    at tryCatcher (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\util.js:26:23)
    at Function.Promise.attempt.Promise.try (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\method.js:31:24)
    at c:\Users\mika\AppData\Roaming\npm\node_modules\facebook-chat-api\utils.js:813:24
    at tryCatcher (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\mika\AppData\Roaming\npm\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```
I tried to upgrade node.js from 9.3.0 to 9.4.0 and reinstalled messer and deleted the appstate.json file. The facebook user which logs into messer works fine from the browser.

**Comment by mjkaufer** [comment]
Yep, these are all currently due to issues with the `facebook-chat-api` dependency, which are due to issues with Facebook, as they recently migrated to GraphQL (this is as I understand it, at least). We'll try to have everything back up and running when `facebook-chat-api` reverse engineers the new messenger GraphQL endpoints.

Sorry for any inconvenience!

**Comment by Canardian** [comment]
Okay, thanks for the info. Now I can don't have to try to debug what's wrong on my side :)

**Comment by tomquirk** [comment]
hey @Canardian , are you still experiencing this?
