### ISSUE TITLE
Message feature not working

### ISSUE THREAD

**Issue by dhruvyadav14** [mjkaufer/Messer#53]
`m "Mike Smith" hello
TypeError: Cannot read property 'name' of undefined
    at Messer.getThreadByName (/usr/local/lib/node_modules/messer/index.js:186:33)
    at Promise (/usr/local/lib/node_modules/messer/src/command-handlers.js:83:29)
    at Promise (<anonymous>)
    at Messer.message (/usr/local/lib/node_modules/messer/src/command-handlers.js:73:12)
    at Messer.processCommand (/usr/local/lib/node_modules/messer/index.js:150:25)
    at REPLServer.eval (/usr/local/lib/node_modules/messer/index.js:128:54)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
    at REPLServer.Interface._ttyWrite (readline.js:904:14)
    at REPLServer.self._ttyWrite (repl.js:502:7)
    at ReadStream.onkeypress (readline.js:157:10)`

For some reason message or m isn't working for a friend named Mike Smith. What could be going on here? Did Facebook update something?

**Comment by mjkaufer** [comment]
See #48 and #52
