### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by sfoubister** [mjkaufer/Messer#66]
Hi
I installed this for the first time and tried to run it but get:

```
$ messer
/usr/lib/node_modules/messer/src/messer.js:60
  )
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> `(/usr/lib/node_modules/messer/index.js:2:16)
```
Thanks
Steve

**Comment by tomquirk** [comment]
Hey @sfoubister , could you please let us know what version of Node you are using?

**Comment by tuananh1406** [comment]
Hi 
I get same error. When i run "npm test", the output is:
```
  1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'test' ]
  3 2 info using npm@4.2.0
  4 3 info using node@v7.10.1
  5 4 verbose config Skipping project config: /home/htuananh/.npmrc. (matches us    erconfig)
  6 5 verbose stack Error: ENOENT: no such file or directory, open '/home/htuana    nh/package.json'
  7 6 verbose cwd /home/htuananh
  8 7 error Linux 4.4.0-128-generic
  9 8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "test"
 10 9 error node v7.10.1
 11 10 error npm  v4.2.0
 12 11 error path /home/htuananh/package.json
 13 12 error code ENOENT
 14 13 error errno -2
 15 14 error syscall open
 16 15 error enoent ENOENT: no such file or directory, open '/home/htuananh/pack    age.json'
 17 16 error enoent ENOENT: no such file or directory, open '/home/htuananh/pack    age.json'
 18 16 error enoent This is most likely not a problem with npm itself
 19 16 error enoent and is related to npm not being able to find a file.
 20 17 verbose exit [ -2, true ]

```
How can i fix that? Thanks!

**Comment by sfoubister** [comment]
Hi @tomquirk 

I am using:

$ node --version
v6.14.0

Cheers
Stephen

**Comment by tomquirk** [comment]
Hey @sfoubister thanks for letting me know your version.

Should be fixed now! Please `npm install` again

**Comment by sfoubister** [comment]
Yep, I can login now.
Thanks
