### ISSUE TITLE
History command is broken

### ISSUE THREAD

**Issue by Unders0und** [mjkaufer/Messer#67]
Whenever I try to access the "history" feature, I got this error... Have I done something wrong? I haven't see anyone complaining about that yet

also... The error got one exception: when I use it on a specific contact, it displays the history as it should, but if I try to specify the number of messages it gives me back the same error I mentioned at the beginning (and which I'll post it fully bellow).

```
(node:1560) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:35:32)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:1560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

I'm running it at my Lubuntu 18.04 LTS...

 update: I realized it only displays the history to the very first person at "recents"

**Comment by Unders0und** [comment]
@tomquirk 
I'm still getting the same error, what do I do?

**Comment by sfoubister** [comment]
I am getting this error, too. Whenever I try to access history:

(node:15701) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): TypeError: Cannot read property 'thread_key' of null

I can only get it to work if I do:

> history "Friend name" 1
Friend name: Lol

It returns just the last message from them. If I try any more it gets the above error

**Comment by tomquirk** [comment]
Hey @Unders0und @sfoubister sorry for the late response to this one...

I'll take a look at this over the weekend, thanks for your patience! (Also, feel free to submit a PR if you think youve got a fix!)

**Comment by Jukiro** [comment]
This error also returns when I try to access a history of a group conversation. Not even 1 recent message can be returned.

**Comment by eupiteco** [comment]
:point_up: Same issue, can't return any messages, like Jukiro above.
Just installed version 0.3.4 via npm in a Manjaro system
Subscribing for fixes. 
Also great app! I've been wating for this a long time :smile:

**Comment by ErikBoesen** [comment]
I'm having the same issue on macOS 10.11.6.

**Comment by tomquirk** [comment]
Ah damn. So weird, I just can't seem to replicate this - `history` works for every situation I can find for me. Any more info you could provide would be awesome. Specifically:
* what position in your thread list is the person (i.e are they most recent, second most etc.)
* how many messages are in that thread
* version of Messer (just to double check)
* What situation (if any) does `history` work for?

Sorry for the trouble everyone

**Comment by eupiteco** [comment]
Hi, I am now running messer in Xubuntu 18.04 and cannot run `messer` as user, only as root... the output is this, I don't remember needing those permissions with 0.3.4
```
permission denied, mkdir '/usr/local/lib/node_modules/messer/src/tmp'
```
But that does not belong in this thread :sweat_smile: 

When running history "User Name" I still get the same error and the prompt hangs. Pressing the enter key results in the following output
 ```
TypeError: Cannot read property 'then' of null
    at REPLServer.eval (/usr/local/lib/node_modules/messer/src/messer.js:141:11)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
    at REPLServer.Interface._ttyWrite (readline.js:911:14)
    at REPLServer.self._ttyWrite (repl.js:537:7)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1011:36)
```
and the `>` prompt is back.

**Comment by Unders0und** [comment]
@tomquirk 
@eupiteco 's case it's the same as mine
since the update, I can only run messer as root

WOOOWWW hold on
the history is working!
well, I can't set the number of messages displayed, but it's working for every contact now 'o'
it's displaying 5 messages

**Comment by tomquirk** [comment]
yep, whoops, I'll fix that `sudo` bug asap.

That error message is different to the one you were getting before @eupiteco, which is promising 😂 It makes a bit more sense to me as well, so I will dig into it later on

**Comment by tomquirk** [comment]
fyi sudo issue solved, things now save to `~/.messer/tmp`

**Comment by tomquirk** [comment]
@eupiteco if you type gibberish into the REPL, does it come back with `Invalid Command - check your syntax`, or the same error?

Otherwise, I'm pretty much at a loss with this bug haha. I've started a branch, `tq_feat/history-bug`, and in it I've made 1 small change which may fix it, who knows. Classic case of `it works on my machine` 😂 😢

**Comment by Unders0und** [comment]
@tomquirk lol
classic programmer issue XD

**Comment by eupiteco** [comment]
Updated to version 0.4.1 via npm and got a different error when trying to login: a `Enter code >` prompt appears after the `Logging in...` message, but it doesn't run anything when pressing enter, just linebreaks; after a while the following message appears:
```
Error: Failed to login as [eupiteco] - [object Object]
    at facebook (/usr/local/lib/node_modules/messer/src/messer.js:108:27)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/index.js:445:7
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

@tomquirk can you give more instructions on running the code in the `history-bug` branch? I am trying `git checkout history-bug` but the output is `error: pathspec 'history-bug' did not match any file(s) known to git.`
`git branch -a` lists the following branches:
```
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/tq_feat/blessed
  remotes/origin/tq_feat/history-bug
```

**Comment by tomquirk** [comment]
ahhhh 💥 Temporary fix for that login issue is to `mkdir ~/.messer`.

The branch is called `tq_feat/history-bug`, so `git checkout tq_feat/history-bug` Let me know how u go!

**Comment by tomquirk** [comment]
Just did another release `0.4.2` - have a play and see if stuff works

**Comment by eupiteco** [comment]
0.4.2 update gives me the following message after `history Person Name`
```
(node:27443) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:35:32)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:27443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After that there is no `>` prompt showing. When I press Enter the following outputs
```
TypeError: Cannot read property 'then' of null
    at REPLServer.eval (/usr/local/lib/node_modules/messer/src/messer.js:144:11)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
    at REPLServer.Interface._ttyWrite (readline.js:911:14)
    at REPLServer.self._ttyWrite (repl.js:537:7)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1011:36)
```
And the `>` prompt is back

Same thing happened with the `tq_feat/history-bug` branch

**Comment by tomquirk** [comment]
just to confim, its `history "person name"` right? (with quotes)

**Comment by eupiteco** [comment]
Yes, "with quotes"

**Comment by tomquirk** [comment]
just released a new version - would love you guys to test it out and see if your history woes are solved!

**Comment by ErikBoesen** [comment]
@tomquirk The same issue still occurs.

**Comment by eupiteco** [comment]
`recent` returns nothing
`history` returns the usual 
```
(node:16259) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:35:32)
    at /home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at tryCatcher (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/eupiteco/.nvm/versions/node/v10.12.0/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
(node:16259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16259) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
```

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a **new** ticket
