### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by plonko** [mjkaufer/Messer#8]
Hullo, I installed NVM and updated Node to 4.2.2 because I saw a warning when I was installing that Messer expected it. Now I get this error when trying to message. 

```
Logged in as sebastianjthomas@gmail.com
> message "Friend name" hello
TypeError: api.sendDirectMessage is not a function
    at REPLServer.repl.start.eval (/usr/local/lib/node_modules/messer/index.js:73:10)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1250:14)
    at next (native)
    at ReadStream.onData (readline.js:918:36)
    at emitOne (events.js:77:13)
```

**Comment by mjkaufer** [comment]
Whoops - looks like `sendDirectMessage` is not a function anymore in https://github.com/Schmavery/facebook-chat-api

Not sure if you want to fix this, but I might look at it once I get done with other stuff

**Comment by Schmavery** [comment]
Guess we can close this now :)

**Comment by mjkaufer** [comment]
Closed - now implementing new `facebook-chat-api` method - thanks @Schmavery
