### ISSUE TITLE
Empty command results in error

### ISSUE THREAD

**Issue by hplewis** [mjkaufer/Messer#82]
When pressing Enter without typing a command, a `TypeError` is displayed to the user.

```
> 
TypeError: Cannot read property 'then' of null
    at REPLServer.eval (/usr/local/lib/node_modules/messer/src/messer.js:144:11)
    at bound (domain.js:396:14)
    at REPLServer.runBound [as eval] (domain.js:409:12)
    at REPLServer.onLine (repl.js:615:10)
    at REPLServer.emit (events.js:182:13)
    at REPLServer.EventEmitter.emit (domain.js:442:20)
    at REPLServer.Interface._onLine (readline.js:290:10)
    at REPLServer.Interface._line (readline.js:638:8)
    at REPLServer.Interface._ttyWrite (readline.js:919:14)
    at REPLServer.self._ttyWrite (repl.js:688:7)
    at ReadStream.onkeypress (readline.js:168:10)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:442:20)
    at emitKeys (internal/readline.js:422:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1022:36)
```

This should probably be handled to not show an error.

**Comment by tomquirk** [comment]
oops 😂 Give that a go

**Comment by hplewis** [comment]
LGTM

**Comment by tomquirk** [comment]
<3
