### ISSUE TITLE
Error when using history

### ISSUE THREAD

**Issue by Yistic** [mjkaufer/Messer#89]
```bash
(node:1633) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'thread_key' of null
    at formatThreadGraphQLResponse (/usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:35:32)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/src/getThreadInfo.js:163:24
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:1633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1633) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tomquirk** [comment]
Hey @Yistic , try updating to messer v0.5.0 and let us know if youre still having trouble :)

**Comment by eupiteco** [comment]
Hello, @Yistic take a look at #67 
Propose to close this as duplicate

**Comment by Yistic** [comment]
Sorry for late reply.I haven't been home for week.Update seems to have fixed this problem.
