### ISSUE TITLE
Error running Messer

### ISSUE THREAD

**Issue by at94official** [mjkaufer/Messer#90]
Hi, I need help. As I try to install and run Messer. I have these errors. 

"Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Administrator>npm install -g messer
C:\Users\Administrator\AppData\Roaming\npm\messer -> C:\Users\Administrator\AppD
ata\Roaming\npm\node_modules\messer\index.js
+ messer@0.4.2
added 131 packages from 86 contributors in 42.883s
C:\Users\Administrator>messer
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Re
ceived type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\messer\src\settings.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\messer\src\messer.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"

and as I used GIT CMD, here is what I got. 

"C:\Users\Administrator>messer
Enter your Facebook credentials - your password will not be visible as you type
it in
prompt: email:  **************
prompt: password:
Logging in...
Error: Failed to login as [********@gmail.com] - [object Object]
    at facebook (C:\Users\Administrator\AppData\Roaming\npm\node_modules\messer\
src\messer.js:108:27)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\messer\node_modul
es\facebook-chat-api\index.js:446:7
    at tryCatcher (C:\Users\Administrator\AppData\Roaming\npm\node_modules\messe
r\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\AppData\Roaming
\npm\node_modules\messer\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\Administrator\AppData\Roaming\npm\node
_modules\messer\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\Administrator\AppData\Roaming\npm\node_
modules\messer\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\Administrator\AppData\Roaming\npm\node_module
s\messer\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\messer\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\messer\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

C:\Users\Administrator>"

**Comment by at94official** [comment]
@tomquirk Yes, hello. Apologies for the late response. I did find the solution and also, I will get these errors if I restrict the access to Facebook.
