### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by lsaadeh** [mjkaufer/Messer#94]
### Description

/usr/local/lib/node_modules/messer/src/messer.js:5
const { getCommandHandler } = require("./commands/command-handlers");
      ^

SyntaxError: Unexpected token {

### Steps to Reproduce

1. npm install -g messer
2. messer
3. ~$ messer
/usr/local/lib/node_modules/messer/src/messer.js:5
const { getCommandHandler } = require("./commands/command-handlers");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/messer/index.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Expected behavior:**
Install messer
Run messer
$ messer
Enter your details
...
Profit

**Actual behavior:**
1. npm install -g messer
2. messer
3. ~$ messer
/usr/local/lib/node_modules/messer/src/messer.js:5
const { getCommandHandler } = require("./commands/command-handlers");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/messer/index.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
4. something something..
5. no profit

### Versions

Run, and copy-paste the results, of the following:
  - npm -v 
3.5.2
  - node -v
v4.2.6
  - messer -v
unable to run

Also, please include the OS and what version of the OS you're running.
Ubuntu 16.04.5 LTS (Xenial Xerus)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lsaadeh** [comment]
node version v4.2.6 too low
