### ISSUE TITLE
Issue on windows 7 with Hyper shell

### ISSUE THREAD

**Issue by mehdi-S** [mjkaufer/Messer#96]
I've installed messer, when I type messer it show me this error 

`path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
`

followed by 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at Object.<anonymous> (C:\Users\t792152\AppData\Roaming\npm\node_modules\messer\node_modules\messen\dist\settings.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

I'm on Windows 7, I use Hyper as terminal, I've nodejs and git installed

**Comment by tomquirk** [comment]
Hey 👋 **Messer 0.5.1 has just been published** with a bunch of bug fixes - install it and give it a whirl 🤘. If you’re still experiencing this issue, please comment below with your symptoms and we'll keep the ticket open. Thanks for supporting Messer 💬

**Comment by tomquirk** [comment]
This issue hasn't had activity in 14 days, so we're assuming it was fixed in a previous release. If it's still an issue, please open a new ticket
