### ISSUE TITLE
Unable to use after facebook phishing block

### ISSUE THREAD

**Issue by sormazi** [mjkaufer/Messer#97]
### Steps to Reproduce

1.  run messer
2. I get this

 `Error: Failed to login: Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
    at facebook_chat_api_1.default (/usr/local/lib/node_modules/messer/node_modules/messen/dist/api.js:51:39)
    at /usr/local/lib/node_modules/messer/node_modules/facebook-chat-api/index.js:447:7
    at tryCatcher (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/messer/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)`

Expected behavior: to log in

Actual behavior: can't log in

### Versions

  - npm 6.7.0
  - node v11.11.0
  - messer 0.5.0

I'm using Mac OS Mojave

**Comment by tomquirk** [comment]
Hey @sormazi , sorry to hear that! Unfortunately, this happens sometimes, and there's nothing we can do about it 😢
